
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
process.env.PRISMA_SCHEMA_DISABLE_ADVISORY_LOCK = "true";
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: process.env.DATABASE_URL || "postgresql://dummy:dummy@localhost:5432/dummy",
    directUrl: process.env.DIRECT_URL || process.env.DATABASE_URL,
  },
});
