import { S3Client, GetObjectCommand } from '@aws-sdk/client-s3';
import fs from 'fs';
import path from 'path';
import { resolveWithinDir } from '@/lib/safe-fetch';

const R2_ACCOUNT_ID = process.env.R2_ACCOUNT_ID || '';
const R2_ACCESS_KEY_ID = process.env.R2_ACCESS_KEY_ID || '';
const R2_SECRET_ACCESS_KEY = process.env.R2_SECRET_ACCESS_KEY || '';
const R2_BUCKET_NAME = process.env.R2_BUCKET_NAME || 'idexo-card-photos';

const isR2Configured = Boolean(
  R2_ACCOUNT_ID && R2_ACCESS_KEY_ID && R2_SECRET_ACCESS_KEY
);

let _s3Client: S3Client | null = null;
function getR2Client(): S3Client | null {
  if (!isR2Configured) return null;
  if (!_s3Client) {
    _s3Client = new S3Client({
      region: 'auto',
      endpoint: `https://${R2_ACCOUNT_ID}.r2.cloudflarestorage.com`,
      credentials: {
        accessKeyId: R2_ACCESS_KEY_ID,
        secretAccessKey: R2_SECRET_ACCESS_KEY,
      },
    });
  }
  return _s3Client;
}

function getContentType(filePath: string): string {
  const ext = path.extname(filePath).toLowerCase();
  switch (ext) {
    case '.png': return 'image/png';
    case '.jpg':
    case '.jpeg': return 'image/jpeg';
    case '.webp': return 'image/webp';
    case '.svg': return 'image/svg+xml';
    case '.gif': return 'image/gif';
    case '.pdf': return 'application/pdf';
    default: return 'application/octet-stream';
  }
}

const TMP_UPLOAD_DIR = path.join('/tmp', 'idexo', 'uploads');

/**
 * Object keys are generated by us (`<prefix>/<timestamp>-<random>.<ext>`), so a
 * segment that is a traversal token, a separator, or a NUL is never legitimate.
 * This route is public, so the check has to happen before either branch — the
 * local one joins the key onto a filesystem path.
 */
function isSafeKeySegment(segment: string): boolean {
  if (!segment || segment === '.' || segment === '..') return false;
  return !/[/\\\0]/.test(segment);
}

export async function GET(
  request: Request,
  { params }: { params: Promise<{ path: string[] }> }
) {
  try {
    const { path: pathSegments } = await params;
    if (!pathSegments || pathSegments.length === 0) {
      return new Response('File path is required', { status: 400 });
    }

    // Percent-encoded separators survive routing, so a single segment can
    // arrive already containing "../". Reject before touching the filesystem.
    if (!pathSegments.every(isSafeKeySegment)) {
      return new Response('File not found', { status: 404 });
    }

    const key = pathSegments.join('/');
    const contentType = getContentType(key);

    // 1. Try local disk fallback first (dev mode or local uploads).
    //    resolveWithinDir is belt-and-braces behind the segment check above.
    const tmpPath = resolveWithinDir(TMP_UPLOAD_DIR, key);
    const publicPath = resolveWithinDir(path.join(process.cwd(), 'public', 'uploads'), key);

    const localFile =
      tmpPath && fs.existsSync(tmpPath) ? tmpPath :
      publicPath && fs.existsSync(publicPath) ? publicPath :
      null;

    if (localFile) {
      const buffer = fs.readFileSync(localFile);
      return new Response(buffer, {
        status: 200,
        headers: {
          'Content-Type': contentType,
          'Cache-Control': 'public, max-age=31536000, immutable',
          'Access-Control-Allow-Origin': '*',
          'X-Content-Type-Options': 'nosniff',
          'Content-Security-Policy': "default-src 'none'; style-src 'unsafe-inline'; sandbox",
        },
      });
    }

    // 2. Fetch from Cloudflare R2 bucket using S3Client if configured
    const s3 = getR2Client();
    if (s3) {
      try {
        const command = new GetObjectCommand({
          Bucket: R2_BUCKET_NAME,
          Key: key,
        });
        const r2Response = await s3.send(command);

        if (r2Response.Body) {
          const byteArray = await r2Response.Body.transformToByteArray();
          const mime = r2Response.ContentType || contentType;

          return new Response(byteArray as any, {
            status: 200,
            headers: {
              'Content-Type': mime,
              'Cache-Control': 'public, max-age=31536000, immutable',
              'Access-Control-Allow-Origin': '*',
              'X-Content-Type-Options': 'nosniff',
              'Content-Security-Policy': "default-src 'none'; style-src 'unsafe-inline'; sandbox",
            },
          });
        }
      } catch (r2Err: any) {
        console.warn(`[API Uploads] R2 fetch error for key "${key}":`, r2Err?.message || r2Err);
      }
    }

    return new Response('File not found', { status: 404 });
  } catch (error: any) {
    console.error('[API Uploads] Error serving asset:', error);
    return new Response('Internal server error', { status: 500 });
  }
}
